/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleProject;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame FBase = new JFrame();

            FBase.setSize(800, 500);
            FBase.setBounds(500, 500, 800, 500);
            FBase.setLayout(null);
            FBase.setVisible(true);
        });
    }
}
